#!/bin/bash
# BUNDA-EUIS File Decryptor v.1
# Created by Prima Setiawan / joeheartless

echo -n "Enter password to decrypt files: "
read -s passwed
echo ""

echo "Password received! Starting decryption..."

# Cari semua file yang terenkripsi (bunda.*)
file_list=$(find . -maxdepth 1 -type f -name "bunda.*")

i=1
for enc in $file_list; do
    original_name="${enc#bunda.}" # Hapus prefix "bunda." buat restore nama asli
    output_file="Un$original_name"
    
    if openssl enc -d -aes-256-cbc -in "$enc" -out "$output_file" -pbkdf2 -k "$passwed"; then
        echo "[$i] Restored file: $output_file"
        rm -f "$enc"  # Hapus file terenkripsi setelah sukses dekripsi
    else
        echo "[ERROR] Gagal dekripsi $enc!"
    fi
    
    i=$((i + 1))
done


